//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialCrm.Models
{

    public partial class Users
    {
        public int UserId { get; set; }
        public string UserNumber { get; set; }
        public string Password { get; set; }
    }
}
